version: "3.9"

services:
  recommendation-ms:
    build: ./backend/recommendation-ms
    ports:
      - "80:80"
    depends_on:
      - neo4j
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USERNAME=myusername
      - NEO4J_PASSWORD=mypassword

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/mypassword