services:
  # <<-- FRONTEND -->>
  app:
    build: ./app
    ports:
      - 3000:3000
    links:
      - signup-login-ms
      - movie-search-ms

  # <<-- BACKEND -->>
  movie-search-ms:
    build:
      context: ./backend/signup-login-ms/
      dockerfile: ../../fastapi.dockerfile
  recommendation-ms:
    build:
      context: ./backend/recommendation-ms/
      dockerfile: ../../fastapi.dockerfile
  user-ms:
    build:
      context: ./backend/user-ms/
      dockerfile: ../../fastapi.dockerfile

  user-db:
    image: mysql:latest #TODO: is latest appropriate?

  watchlist-ms:
    build:
      context: ./backend/watchlist-ms/
      dockerfile: ../../fastapi.dockerfile
  watchlist-db:
    image: cassandra:latest #TODO: is latest appropriate?

  analytics-ms:
    build:
      context: ./backend/analytics-ms/
      dockerfile: ../../fastapi.dockerfile
  analytics-db:
    image: neo4j:latest #TODO: is latest appropriate?
