version: "2"
services:
  # <<-- FRONTEND -->>
  #app:
  #  build: ./app
  #  ports:
  #    - 3000:3000

  # <<-- BACKEND -->>
  user-ms:
    build: ./backend/user-ms/
    ports:
     - '3360:3360'
    expose:
     - '3360'
    depends_on:
      user-db:
        condition: service_healthy
    links:
     - user-db
  
  user-db:
    image: mysql:latest
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_HOST: "used-db"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306"]
      interval: 10s
      timeout: 30s
      retries: 5
